version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD:   # Alterar a sua senha root do MYSQL
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db/sql/bdAPI.sql:/docker-entrypoint-initdb.d/bdAPI.sql 
    networks:
      - internet
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - '5001:5000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internet

volumes:
  db-data:

networks:
  internet:
    driver: bridge