version: '3.8'

services:
  database:
    image: 'bitnami/mysql:latest'
    container_name: 'smart-farming-mysql'
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
